#include "stdafx.h"
#include <memory>
#include <opencv2/videoio.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>
#include <cvblob.h>
using namespace std;
using namespace cv;
using namespace cvb;


void ProcessVideo(const string& videoFilename)
{
	// Current frame
	Mat frame;
	// Foreground mask generated by MOG2 method
	Mat fgMaskMOG2;
	// Background
	Mat bgImg;
	// MOG2 Background subtractor
	Ptr<BackgroundSubtractorMOG2> pMOG2 = createBackgroundSubtractorMOG2(200, 36.0, false);

	while (true)
	{
		VideoCapture capture(videoFilename);
		if (!capture.isOpened())
		{
			cerr << "Unable to open video file: " << videoFilename << endl;
			return;
		}

		int width = (int)capture.get(CV_CAP_PROP_FRAME_WIDTH);
		int height = (int)capture.get(CV_CAP_PROP_FRAME_HEIGHT);

		unique_ptr<IplImage, void(*)(IplImage*)> labelImg(
			cvCreateImage(cvSize(width, height), IPL_DEPTH_LABEL, 1), 
			[](IplImage* p){ cvReleaseImage(&p); }
		);
		CvBlobs blobs;
		CvTracks tracks;

		while (true)
		{
			// Read input data. Press ESC or Q to quit
			int key = waitKey(1);
			if (key == 'q' || key == 27)
				return;
			if (!capture.read(frame))
				break;

			// Update background
			pMOG2->apply(frame, fgMaskMOG2);
			pMOG2->getBackgroundImage(bgImg);
			imshow("BG", bgImg);
			imshow("Original mask", fgMaskMOG2);

			// Post process
			medianBlur(fgMaskMOG2, fgMaskMOG2, 5);
			imshow("medianBlur", fgMaskMOG2);
			// Fill black holes
			morphologyEx(fgMaskMOG2, fgMaskMOG2, MORPH_CLOSE, getStructuringElement(MORPH_RECT, Size(5, 5)));
			// Fill white holes
			morphologyEx(fgMaskMOG2, fgMaskMOG2, MORPH_OPEN, getStructuringElement(MORPH_RECT, Size(5, 5)));
			imshow("morphologyEx", fgMaskMOG2);

			// Track
			cvLabel(&IplImage(fgMaskMOG2), labelImg.get(), blobs);
			cvFilterByArea(blobs, 64, 10000);
			cvUpdateTracks(blobs, tracks, 10, 90, 30);
			cvRenderTracks(tracks, &IplImage(frame), &IplImage(frame));

			// Show
			imshow("Frame", frame);

			key = waitKey(30);
		}
	}
}

int main(int argc, char* argv[])
{
	if (argc != 2)
	{
		cout << "Usage: VehicleDetection.exe videofile" << endl;
		return 1;
	}

	ProcessVideo(argv[1]);

	cvDestroyAllWindows();
	return 0;
}
